### ISSUE TITLE
Add ImageGoNord credits

### ISSUE THREAD

**Issue by TheJoin95** [sourav2k/Nord-Wallpapers#1]
Please add Schrodinger-hat/ImageGoNord credits on the readme

**Comment by theglitchh** [comment]
MIT LICENSE, so not required

**Comment by TheJoin95** [comment]
We put MIT License in order to help other to create their ideas using or modifying our tool :)
By using the tool it would be helpful to share the love and the project in order to give some support, it does not cost anything and maybe it will give us some visibility, also to try to achieve something more in the future and improving our demo website to grant to any level of users the tool :)

Thank you for your understanding 👍

**Comment by sourav2k** [comment]
will create a new issue on it
